title: Matheos Giakoumi # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <i><b>MBA, MEng, BS</b></i>
  <br>
  <b>Mechanical & Materials Science Engineer</b>
  <b>Petroleum Engineer</b>
  <br>
  <b><u>Researcher at:</u></b>
  <br>
  <a href = "https://www.feem.it/en/ricerca/programmi/technologies-for-the-energy-transition/" target="_blank">Fondazione Eni Enrico Mattei</a>
  <br>
  <a href = "https://websites.ucy.ac.cy/energygeomechanics/" target="_blank">University of Cyprus</a>
  <br>
  <a href = "http://biolisys.cut.ac.cy/" target="_blank">Cyprus University of Technology</a>
  <br><br>
  Seeking PhD opportunities in Geoscience & Energy Engineering

theme: jekyll-theme-minimal
