title: Matheos Giakoumi 
logo: "/images/logo.png?raw=true" 
description: > 
  <i><b>PhD Student @ UT Austin PGE</b></i>
  <br>
  <a href="https://www.linkedin.com/in/matheos-giakoumi-5890672a2?originalSubdomain=en" target="_blank">LinkedIn</a> | 
  <a href="https://scholar.google.com/citations?user=kuQiByUAAAAJ&hl=en" target="_blank">Google Scholar</a> | 
    <a href="https://1drv.ms/b/c/02e2e71e1116e8cc/ESauUygW1aJEsma30nIS6hkBNhST_kl1Wfx6EcnOokD3Ug?e=qL8r5r" target="_blank">Resume</a> |
  <a href="https://www.researchgate.net/profile/Matheos-Giakoumi" target="_blank">ResearchGate</a> 


theme: jekyll-theme-minimal
